MINUTES_START_VALUE = 0
MINUTES_END_VALUE = 59
MINUTES_FIELD_NAME = "minutes"

HOURS_START_VALUE = 0 
HOURS_END_VALUE = 23
HOURS_FIELD_NAME = "hour"

DAY_OF_MONTH_START_VALUE = 1
DAY_OF_MONTH_END_VALUE = 31
DAY_OF_MONTH_FIELD_NAME = "day of month"

MONTHS_START_VALUE = 1
MONTHS_END_VALUE = 12
MONTHS_FIELD_NAME = "month"

DAY_OF_WEEK_START_VALUE = 1
DAY_OF_WEEK_END_VALUE = 7
DAY_OF_WEEK_FIELD_NAME = "day of week"

COMMAND_FIELD_NAME = "command"